modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

authors="Shadows_of_Fire" #optional

[[mods]] #mandatory

modId="compatchedstorage" #mandatory

version="${file.jarVersion}" #mandatory

displayName="ComPatchedStorage" #mandatory

description='''
Holding many things in a tiny space.
'''

[[dependencies.compatchedstorage]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.compatchedstorage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.compatchedstorage]]
    modId="placebo"
    mandatory=true
    versionRange="[3,)"
    ordering="NONE"
    side="BOTH"